### ISSUE TITLE
Randomise Failblog posts

### ISSUE THREAD

**Issue by markunsworth** [ben-biddington/Coriander.Haarlem#9]
Rather than taking the most recent failblog post, could they be randomised. I have a lot of broken builds so get bored of seeing the same failblog post

**Comment by ben-biddington** [comment]
Lots of failed builds, huh?

**Comment by markunsworth** [comment]
When I say I have, I mean I can see, mostly API and Assetserver

**Comment by markunsworth** [comment]
i'm assuming you're not going to do this Bin
